name: Prepare Workspace
description: Prepares and initializes the workspace
runs:
    using: composite
    steps:
        - name: Check formatting
          shell: bash
          run: npx nx format:check

        - name: Check linting
          shell: bash
          run: npx nx run-many -t lint

        - name: Compile projects
          shell: bash
          run: npx nx run-many -t build

        - name: Run tests
          shell: bash
          run: npx nx run-many -t test
