name: Create tags

on:
    pull_request:
        types:
            - closed

permissions:
    contents: true

jobs:
    create-tags:
        if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'release/')
        name: Create tags
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Extract version
              run: |
                  version=$(grep '"version"' package.json | sed -E 's/.*"version": "(.*)".*/\1/')
                  echo "VERSION=$version" >> $GITHUB_ENV

            - name: Create tags
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.email "github-actions@github.com"
                  git config --global user.name "Github Actions"

                  git tag ${{ env.VERSION }}
                  git push origin ${{ env.VERSION }}
