name: Release

on:
    pull_request:
        types:
            - closed

permissions:
    contents: write

jobs:
    release:
        if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'release/')
        name: Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Prepare Workspace
              uses: ./.github/actions/prepare-workspace
              with:
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract version
              run: |
                  version=$(grep '"version"' package.json | sed -E 's/.*"version": "(.*)".*/\1/')
                  echo "VERSION=$version" >> $GITHUB_ENV

            - name: Create installers
              run: npx nx create-installers

            - name: Create installer bundles
              uses: ./.github/actions/create-installer-bundles

            - name: Create release bundle
              run: ts-node tools/prepare-release-package.ts

            - name: Create tags
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.email "github-actions@github.com"
                  git config --global user.name "Github Actions"

                  git tag ${{ env.VERSION }}
                  git push origin ${{ env.VERSION }}

            - name: Publish release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ env.VERSION }}
                  tag_name: ${{ env.VERSION }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  files: |
                      windows-installer.zip
                      mac-x64-installer.zip
                      mac-arm64-installer.zip

            - name: Upload release bundle
              uses: actions/upload-artifact@v4
              with:
                  name: release-bundle
                  path: |
                      dist/executables/_release/*
